pipeline:
  identifier: Build_harshavardhanswiggy_java_example_1726548867778
  name: Build java-example
  orgIdentifier: default
  projectIdentifier: swiggy
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: harshavardhanswiggy/java-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: echo
                  identifier: echo
                  spec:
                    shell: Sh
                    command: |-
                      echo Hello World

                      mvn clean install
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
