pipeline:
  identifier: Build_harshavardhanswiggy_java_example_1726548867778
  name: Build java-example
  orgIdentifier: default
  projectIdentifier: swiggy
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: harshavardhanswiggy/java-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: echo
                  spec:
                    shell: Sh
                    command: |-
                      #echo Hello World

                      sed -i '/<\/dependencies>/i \
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-controls</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-fxml</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-base</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-graphics</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-swing</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>net.java.dev.jna</groupId>\n\
                              <artifactId>jna</artifactId>\n\
                              <version>5.8.0</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>net.java.dev.jna</groupId>\n\
                              <artifactId>jna-platform</artifactId>\n\
                              <version>5.8.0</version>\n\
                          <\/dependency>' pom.xml && \
                          sed -i '/<build>/a \
                          <plugins>\n\
                              <plugin>\n\
                                  <groupId>org.apache.maven.plugins</groupId>\n\
                                  <artifactId>maven-surefire-plugin</artifactId>\n\
                                  <version>3.0.0-M5</version>\n\
                                  <configuration>\n\
                                      <skipTests>true</skipTests>\n\
                                  <\/configuration>\n\
                              <\/plugin>\n\
                              <plugin>\n\
                                  <groupId>org.apache.maven.plugins</groupId>\n\
                                  <artifactId>maven-assembly-plugin</artifactId>\n\
                                  <configuration>\n\
                                      <archive>\n\
                                          <manifestFile>${basedir}/target/classes/META-INF/MANIFEST.MF<\/manifestFile>\n\
                                      <\/archive>\n\
                                  <\/configuration>\n\
                              <\/plugin>\n\
                              <plugin>\n\
                                  <groupId>org.apache.maven.plugins</groupId>\n\
                                  <artifactId>maven-jar-plugin</artifactId>\n\
                                  <version>2.5<\/version>\n\
                                  <configuration>\n\
                                      <archive>\n\
                                          <manifestFile>${basedir}/target/classes/META-INF/MANIFEST.MF<\/manifestFile>\n\
                                          <manifest>\n\
                                              <addClasspath>true<\/addClasspath>\n\
                                              <mainClass>com.openfin.desktop.demo.OpenFinDesktopDemo<\/mainClass>\n\
                                          <\/manifest>\n\
                                      <\/archive>\n\
                                  <\/configuration>\n\
                                  <executions>\n\
                                      <execution>\n\
                                          <goals>\n\
                                              <goal>test-jar<\/goal>\n\
                                          <\/goals>\n\
                                      <\/execution>\n\
                                  <\/executions>\n\
                              <\/plugin>\n\
                              <plugin>\n\
                                  <groupId>org.apache.maven.plugins</groupId>\n\
                                  <artifactId>maven-dependency-plugin</artifactId>\n\
                                  <executions>\n\
                                      <execution>\n\
                                          <id>copy<\/id>\n\
                                          <phase>install<\/phase>\n\
                                          <goals>\n\
                                              <goal>copy-dependencies<\/goal>\n\
                                          <\/goals>\n\
                                          <configuration>\n\
                                              <outputDirectory>${project.build.directory}<\/outputDirectory>\n\
                                          <\/configuration>\n\
                                      <\/execution>\n\
                                  <\/executions>\n\
                              <\/plugin>\n\
                          <\/plugins>' pom.xml


                      cat pom.xml

                      mvn clean install -DskipTests=false -DtestFailureIgnore=true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
