pipeline:
  identifier: Build_harshavardhanswiggy_java_example_1726548867778
  name: Build java-example
  orgIdentifier: default
  projectIdentifier: swiggy
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: harshavardhanswiggy/java-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: echo
                  spec:
                    shell: Sh
                    command: |-
                      #echo Hello World

                      sed -i '/<\/dependencies>/i \
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-controls</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-fxml</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-base</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-graphics</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>\n\
                          <dependency>\n\
                              <groupId>org.openjfx</groupId>\n\
                              <artifactId>javafx-swing</artifactId>\n\
                              <version>17.0.1</version>\n\
                          <\/dependency>' pom.xml




                      mvn clean install
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
